services:
  frontend:
    build:
      dockerfile: Dockerfile
    image: "ghcr.io/matevz/demo-rofl-www:nc"
    ports:
      - "10000:10000"
    annotations:
      net.oasis.proxy.ports.10000.mode: passthrough
